name       : libixion
version    : 0.12.2
release    : 3
source     :
    - http://kohei.us/files/ixion/src/libixion-0.12.2.tar.xz : 8b44008836bb4e1a3dff4d3e40afec6c73037e3518e72cc85b5cc675fbc2daae
license    : MPL-2.0
component  : programming
summary    : General purpose formula parser & interpreter
description: |
    Ixion is a general purpose formula parser & interpreter that can calculate multiple named targets, or "cells".
builddeps  :
    - pkgconfig(mdds-1.2)
    - pkgconfig(python3)
    - libboost-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
