name       : libixion
version    : 0.14.1
release    : 8
source     :
    - https://gitlab.com/ixion/ixion/-/archive/0.14.1/ixion-0.14.1.tar.bz2 : 611ea0040ac700f3e24bb7e627fd2a8f3234157df0d1e8fa37cf9d4b13593a1f
license    : MPL-2.0
component  : programming
summary    : General purpose formula parser & interpreter
description: |
    Ixion is a general purpose formula parser & interpreter that can calculate multiple named targets, or "cells".
builddeps  :
    - pkgconfig(mdds-1.4)
    - pkgconfig(python3)
    - libboost-devel
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
