name       : libixion
version    : 0.11.1
release    : 1
source     :
    - http://kohei.us/files/ixion/src/libixion-0.11.1.tar.xz : c9e9f52580d618fa969fc0293f55af21a9c74bfb802e655c6bf239202f95bede
license    : MPL-2.0
component  : programming
summary    : General purpose formula parser & interpreter
description: |
    Ixion is a general purpose formula parser & interpreter that can calculate multiple named targets, or "cells".
builddeps  :
    - pkgconfig(mdds-1.2)
    - pkgconfig(python3)
    - libboost-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
