name       : libixion
version    : 0.17.0
release    : 21
source     :
    - https://gitlab.com/ixion/ixion/-/archive/0.17.0/ixion-0.17.0.tar.gz : 5a016c978ba3f6931b7dbb7581c188817f8244aa8445c31b94613a2dea462f54
license    : MPL-2.0
component  : programming
summary    : General purpose formula parser & interpreter
description: |
    Ixion is a general purpose formula parser & interpreter that can calculate multiple named targets, or "cells".
builddeps  :
    - pkgconfig(mdds-2.0)
    - pkgconfig(python3)
    - pkgconfig(spdlog)
    - libboost-devel
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
